if(NOT DEFINED APPLICATION_ICON_NAME)
    set(APPLICATION_ICON_NAME "${APPLICATION_SHORTNAME}")
endif()

file(GLOB_RECURSE APPLICATION_ICONS "${OEM_THEME_DIR}/theme/colored/*-${APPLICATION_ICON_NAME}-icon.png")
if(NOT APPLICATION_ICONS)
    app_generate_legacy_icons(${OEM_THEME_DIR}/theme APPLICATION_ICONS)
endif()
message(STATUS "APPLICATION_ICONS: ${APPLICATION_ICON_NAME}: ${APPLICATION_ICONS}")

set(EXCLUDE_FILE_NAME "sync-exclude.lst")

if(APPLE)
    list(APPEND APPLICATION_BUNDLED_RESOURCES "${CMAKE_CURRENT_SOURCE_DIR}/${EXCLUDE_FILE_NAME}")
else()
    configure_file("${EXCLUDE_FILE_NAME}" "bin/${EXCLUDE_FILE_NAME}" COPYONLY)
    install(FILES "${EXCLUDE_FILE_NAME}" DESTINATION "${APP_INSTALL_BINDIR}")
endif()
